import { OnePoleLowpass, clamp } from "../../dsp/primitives";
import { EFFECT_TRANSPORT_TEMPO_PARAMETER, booleanState, enumState, finite, numberState, writeStereoFrame, type EffectFrameProcessor, type EffectState, type StereoFrame } from "../dsp";
export class DelayDsp implements EffectFrameProcessor {
  readonly #sampleRate: number; readonly #state: EffectState; readonly #left: Float32Array; readonly #right: Float32Array; readonly #leftFilter = new OnePoleLowpass(); readonly #rightFilter = new OnePoleLowpass(); #write = 0; #delayFrames: number;
  constructor(sampleRate: number, state: EffectState) { this.#sampleRate = sampleRate; this.#state = state; this.#left = new Float32Array(Math.ceil(sampleRate * 2.1)); this.#right = new Float32Array(this.#left.length); this.#delayFrames = this.#targetDelayFrames(); }
  reset(): void { this.#left.fill(0); this.#right.fill(0); this.#leftFilter.reset(); this.#rightFilter.reset(); this.#write = 0; this.#delayFrames = this.#targetDelayFrames(); }
  #targetDelayFrames(): number { const synced = booleanState(this.#state, "tempo-sync", true); const milliseconds = synced ? (60_000 / numberState(this.#state, EFFECT_TRANSPORT_TEMPO_PARAMETER, 120, 40, 240)) * numberState(this.#state, "beat-time", 0.5, 0.0625, 4) : numberState(this.#state, "time", 375, 10, 2000); return clamp(milliseconds * this.#sampleRate / 1000, 1, this.#left.length - 2); }
  #read(buffer: Float32Array): number { const position = (this.#write - this.#delayFrames + buffer.length) % buffer.length; const lower = Math.floor(position), fraction = position - lower; const upper = (lower + 1) % buffer.length; return (buffer[lower] ?? 0) * (1 - fraction) + (buffer[upper] ?? 0) * fraction; }
  process(left: number, right: number, output?: StereoFrame): StereoFrame { const target = this.#targetDelayFrames(); this.#delayFrames += clamp(target - this.#delayFrames, -0.25, 0.25); const delayedLeft = this.#read(this.#left), delayedRight = this.#read(this.#right); const pingPong = booleanState(this.#state, "ping-pong", true), feedback = numberState(this.#state, "feedback", 0.42, 0, 0.92), cutoff = numberState(this.#state, "filter", 4800, 300, 18000); const sourceLeft = pingPong ? delayedRight : delayedLeft, sourceRight = pingPong ? delayedLeft : delayedRight; let feedbackLeft = this.#leftFilter.process(sourceLeft, cutoff, this.#sampleRate), feedbackRight = this.#rightFilter.process(sourceRight, cutoff, this.#sampleRate); if (enumState(this.#state, "mode", "analog" as const, ["analog", "clean"] as const) === "analog") { feedbackLeft = Math.tanh(feedbackLeft * 1.15) / 1.15; feedbackRight = Math.tanh(feedbackRight * 1.15) / 1.15; } this.#left[this.#write] = finite(left + feedbackLeft * feedback); this.#right[this.#write] = finite(right + feedbackRight * feedback); this.#write = (this.#write + 1) % this.#left.length; return writeStereoFrame(output, finite(delayedLeft), finite(delayedRight)); }
}

export function createEffectProcessor(sampleRate: number, state: EffectState): EffectFrameProcessor {
  return new DelayDsp(sampleRate, state);
}
