import { OnePoleLowpass, clamp } from "../../dsp/primitives";
import { finite, numberState, writeStereoFrame, type EffectFrameProcessor, type EffectState, type StereoFrame } from "../dsp";
const PRIME_DELAYS = [0.0297, 0.0371, 0.0411, 0.0437] as const;
export class ReverbDsp implements EffectFrameProcessor {
  readonly #sampleRate: number; readonly #state: EffectState; readonly #lines: readonly Float32Array[]; readonly #positions = [0, 0, 0, 0]; readonly #filters = [new OnePoleLowpass(), new OnePoleLowpass(), new OnePoleLowpass(), new OnePoleLowpass()]; readonly #preDelay: Float32Array; readonly #shimmerBuffer: Float32Array; #preWrite = 0; #shimmerWrite = 0; #shimmerPhase = 0;
  constructor(sampleRate: number, state: EffectState) { this.#sampleRate = sampleRate; this.#state = state; this.#lines = PRIME_DELAYS.map((seconds) => new Float32Array(Math.max(1, Math.round(seconds * sampleRate)))); this.#preDelay = new Float32Array(Math.max(1, Math.round(sampleRate * 0.2) + 1)); this.#shimmerBuffer = new Float32Array(Math.max(16, Math.round(sampleRate * 0.05))); }
  reset(): void { for (const line of this.#lines) line.fill(0); this.#preDelay.fill(0); this.#shimmerBuffer.fill(0); this.#positions.fill(0); for (const filter of this.#filters) filter.reset(); this.#preWrite = 0; this.#shimmerWrite = 0; this.#shimmerPhase = 0; }
  #readShimmer(phase: number): number { const delay = (1 - phase) * (this.#shimmerBuffer.length - 2); const position = (this.#shimmerWrite - delay + this.#shimmerBuffer.length) % this.#shimmerBuffer.length; const index = Math.floor(position), fraction = position - index; return (this.#shimmerBuffer[index] ?? 0) * (1 - fraction) + (this.#shimmerBuffer[(index + 1) % this.#shimmerBuffer.length] ?? 0) * fraction; }
  #shimmer(input: number): number { this.#shimmerBuffer[this.#shimmerWrite] = input; const phaseA = this.#shimmerPhase, phaseB = (phaseA + 0.5) % 1; const windowA = 0.5 - 0.5 * Math.cos(2 * Math.PI * phaseA), windowB = 0.5 - 0.5 * Math.cos(2 * Math.PI * phaseB); const output = (this.#readShimmer(phaseA) * windowA + this.#readShimmer(phaseB) * windowB) / Math.max(0.5, windowA + windowB); this.#shimmerWrite = (this.#shimmerWrite + 1) % this.#shimmerBuffer.length; this.#shimmerPhase = (this.#shimmerPhase + 1 / this.#shimmerBuffer.length) % 1; return output; }
  process(left: number, right: number, output?: StereoFrame): StereoFrame { const mono = (finite(left) + finite(right)) * 0.5; const preFrames = Math.round(numberState(this.#state, "pre-delay", 22, 0, 200) * this.#sampleRate / 1000); const preRead = (this.#preWrite - preFrames + this.#preDelay.length) % this.#preDelay.length; const input = this.#preDelay[preRead] ?? 0; this.#preDelay[this.#preWrite] = mono; this.#preWrite = (this.#preWrite + 1) % this.#preDelay.length; const decay = numberState(this.#state, "decay", 2.8, 0.2, 12), damping = numberState(this.#state, "damping", 6200, 500, 18000); let sum = 0; for (let index = 0; index < this.#lines.length; index += 1) { const line = this.#lines[index]; if (line === undefined) continue; const position = this.#positions[index] ?? 0; const delayed = line[position] ?? 0; const filtered = this.#filters[index]?.process(delayed, damping, this.#sampleRate) ?? 0; const feedback = Math.exp(-3 * line.length / (this.#sampleRate * decay)); line[position] = finite(input * 0.25 + (filtered - sum * 0.08) * feedback); this.#positions[index] = (position + 1) % line.length; sum += delayed; } const shimmer = numberState(this.#state, "shimmer", 0, 0, 1); const shifted = this.#shimmer(sum); const wet = clamp(sum * 0.25 + shifted * shimmer * 0.12, -4, 4); return writeStereoFrame(output, finite(wet), finite(wet * 0.7)); }
}

export function createEffectProcessor(sampleRate: number, state: EffectState): EffectFrameProcessor {
  return new ReverbDsp(sampleRate, state);
}
